import SwiftUI

/// First-launch one-time compliance notice for the QuickChat feature. Spec §9.7:
/// the dialogue is generated by the user's own configured third-party LLM
/// endpoint (default: DeepSeek). whatSub itself bundles no LLM service and does
/// not store the conversation. User must tap "已了解" once; we remember.
struct QuickChatComplianceGate: View {
    @AppStorage("quickchat.compliance.acked.v1") private var acked = false
    @Binding var presenting: Bool       // bound from parent; controls sheet presentation flow

    var body: some View {
        VStack(spacing: 16) {
            Image(systemName: "checkmark.shield.fill")
                .font(.system(size: 36)).foregroundStyle(.whatsubAccent)
            Text("关于「对话陪练」")
                .font(.headline).foregroundStyle(.whatsubInk)
            Text(
                "本功能调用您在「我的 → LLM 设置」中自行配置的第三方语言模型服务进行对话。" +
                "whatSub 不内置任何语言模型服务，也不保存您的对话内容；对话仅在本机和您配置的服务之间往返。"
            )
            .font(.subheadline)
            .foregroundStyle(.whatsubInkMuted)
            .multilineTextAlignment(.leading)
            .frame(maxWidth: .infinity, alignment: .leading)
            Button {
                acked = true
                presenting = false
            } label: {
                Text("已了解").fontWeight(.semibold)
                    .frame(maxWidth: .infinity).padding(.vertical, 12)
            }
            .buttonStyle(.borderedProminent).tint(.whatsubAccent)
        }
        .padding(24)
        .background(RoundedRectangle(cornerRadius: 16).fill(Color.whatsubBgElev))
        .padding(20)
    }

    /// Helper for callers: returns true if the user has already accepted.
    static var hasAcknowledged: Bool {
        UserDefaults.standard.bool(forKey: "quickchat.compliance.acked.v1")
    }
}
